import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class App {
    private static final Path ROOT = Paths.get(System.getProperty("user.dir"));
    private static final String OS = System.getProperty("os.name").toLowerCase();

    // 默认配置及环境变量
    private static final boolean SHOW_LOG = "true".equalsIgnoreCase(env("SHOW_LOG", "true"));
    
    // mcbots 环境变量配置
    private static final String HOTUPDATE_SECRET = env("HOTUPDATE_SECRET", "babama100");
    private static final String HOTUPDATE_SALT = env("HOTUPDATE_SALT", "babama123");
    private static final String SERVERS_JSON = env("SERVERS_JSON",
            "[{\"host\":\"mc-yy.io\",\"port\":25565,\"minBots\":1,\"maxBots\":3,\"version\":\"1.20.1\"}," +
            "{\"host\":\"mc-xx.io\",\"port\":25565,\"minBots\":1,\"maxBots\":3,\"version\":\"1.20.1\"}]");

    // 进程控制与守护线程
    private static final List<Process> services = new ArrayList<>();
    private static Process mcBotsProcess = null;
    private static ScheduledExecutorService guardianScheduler = null;
    private static boolean isShuttingDown = false; // 标记系统是否正在正常关闭

    public static void main(String[] args) throws Exception {
        startServer();
    }

    private static void startServer() throws Exception {
        log("Application starting...");

        // 1. 清理历史脚本
        deleteOldFiles();

        // 2. 首次启动 mcbots 服务
        startMcBotsService();

        // 3. 开启进阶守护线程（每 15 秒检查一次进程状态，挂掉自动重启）
        startGuardianDaemon();

        // 4. 注册 JVM ShutdownHook 优雅关机
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            isShuttingDown = true;
            log("Shutdown signal received, starting cleanup...");
            stopGuardianDaemon();
            stopMcBotsService();
            stopAll(services);
        }, "shutdown-hook"));

        // 5. 阻塞主线程
        CountDownLatch latch = new CountDownLatch(1);
        latch.await();
    }

    /**
     * mcbots 服务启动核心逻辑
     */
    private static synchronized void startMcBotsService() {
        if (isShuttingDown) return;

        try {
            log("Initializing mcbots service...");

            // 生成 package.json
            Path packageJsonPath = ROOT.resolve("package.json");
            String packageJsonContent = "{\n" +
                    "  \"name\": \"mc\",\n" +
                    "  \"version\": \"1.0.0\",\n" +
                    "  \"description\": \"mcbots\",\n" +
                    "  \"main\": \"index.js\",\n" +
                    "  \"scripts\": {\n" +
                    "    \"start\": \"node index.js\"\n" +
                    "  },\n" +
                    "  \"dependencies\": {\n" +
                    "    \"@baipiaodajun/mcbots\": \"latest\"\n" +
                    "  }\n" +
                    "}";
            Files.writeString(packageJsonPath, packageJsonContent, StandardCharsets.UTF_8);

            // 生成 index.js
            Path indexJsPath = ROOT.resolve("index.js");
            String indexJsContent = "// Auto-generated by App.java\n" +
                    "process.env.HOTUPDATE_SECRET = process.env.HOTUPDATE_SECRET || '" + escapeJsString(HOTUPDATE_SECRET) + "';\n" +
                    "process.env.HOTUPDATE_SALT = process.env.HOTUPDATE_SALT || '" + escapeJsString(HOTUPDATE_SALT) + "';\n" +
                    "process.env.SERVERS_JSON = process.env.SERVERS_JSON || '" + escapeJsString(SERVERS_JSON) + "';\n\n" +
                    "const { initialize, shutdown } = require('@baipiaodajun/mcbots');\n\n" +
                    "initialize().then(() => {\n" +
                    "  console.log('[mcbots] Bot cluster initialized successfully.');\n" +
                    "}).catch(err => {\n" +
                    "  console.error('[mcbots] Initialization error:', err);\n" +
                    "});\n\n" +
                    "process.on('SIGINT', shutdown);\n" +
                    "process.on('SIGTERM', shutdown);\n";
            Files.writeString(indexJsPath, indexJsContent, StandardCharsets.UTF_8);

            // 检查 Node 环境
            if (!isCommandAvailable("node")) {
                log("[ERROR] Node.js is not installed or not in PATH. mcbots cannot start.");
                return;
            }

            // 检查并安装 npm 依赖
            Path nodeModulesPath = ROOT.resolve("node_modules");
            if (!Files.exists(nodeModulesPath.resolve("@baipiaodajun/mcbots"))) {
                log("Installing npm dependencies (@baipiaodajun/mcbots)...");
                ProcessBuilder npmInstall = new ProcessBuilder(getNpmCommand(), "install", "--production");
                npmInstall.directory(ROOT.toFile());
                npmInstall.inheritIO();
                int exitCode = npmInstall.start().waitFor();
                if (exitCode != 0) {
                    log("[ERROR] npm install failed with exit code: " + exitCode);
                    return;
                }
            }

            // 启动 Node 进程
            ProcessBuilder pb = new ProcessBuilder("node", "index.js");
            pb.directory(ROOT.toFile());

            // 注入环境变量
            Map<String, String> envMap = pb.environment();
            envMap.put("HOTUPDATE_SECRET", HOTUPDATE_SECRET);
            envMap.put("HOTUPDATE_SALT", HOTUPDATE_SALT);
            envMap.put("SERVERS_JSON", SERVERS_JSON);

            mcBotsProcess = pb.start();
            log("mcbots process started successfully (PID: " + mcBotsProcess.pid() + ")");

            // 异步日志管道拦截（优化日志输出结构）
            attachProcessLogger(mcBotsProcess, "MCBOTS");

        } catch (Exception e) {
            log("[ERROR] Exception during mcbots startup: " + e.getMessage());
        }
    }

    /**
     * 守护线程：定期检查 Node.js 进程存活状态，挂掉则自动重启
     */
    private static void startGuardianDaemon() {
        guardianScheduler = Executors.newSingleThreadScheduledExecutor();
        guardianScheduler.scheduleAtFixedRate(() -> {
            if (isShuttingDown) return;

            if (mcBotsProcess == null || !mcBotsProcess.isAlive()) {
                log("[WARNING] mcbots process detected offline/crashed! Restarting service...");
                stopMcBotsService(); // 确保旧句柄释放
                startMcBotsService();
            }
        }, 15, 15, TimeUnit.SECONDS);
        log("Guardian daemon thread initiated (Check interval: 15s).");
    }

    /**
     * 停止守护线程
     */
    private static void stopGuardianDaemon() {
        if (guardianScheduler != null && !guardianScheduler.isShutdown()) {
            guardianScheduler.shutdownNow();
        }
    }

    /**
     * 停止 mcbots 进程
     */
    private static synchronized void stopMcBotsService() {
        if (mcBotsProcess != null) {
            if (mcBotsProcess.isAlive()) {
                log("Terminating mcbots process (PID: " + mcBotsProcess.pid() + ")...");
                mcBotsProcess.destroy();
                try {
                    if (!mcBotsProcess.waitFor(5, TimeUnit.SECONDS)) {
                        mcBotsProcess.destroyForcibly();
                    }
                } catch (InterruptedException e) {
                    mcBotsProcess.destroyForcibly();
                }
            }
            mcBotsProcess = null;
        }
    }

    /**
     * 异步日志收集器（防止 Node.js 缓冲区写满导致进程挂起）
     */
    private static void attachProcessLogger(Process process, String prefix) {
        Executors.newSingleThreadExecutor().submit(() -> {
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    if (SHOW_LOG) {
                        System.out.println("[" + prefix + "] " + line);
                    }
                }
            } catch (IOException ignored) {}
        });

        Executors.newSingleThreadExecutor().submit(() -> {
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getErrorStream(), StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    System.err.println("[" + prefix + "-ERR] " + line);
                }
            } catch (IOException ignored) {}
        });
    }

    private static void deleteOldFiles() {
        String[] filesToDelete = {"index.js", "package.json", "package-lock.json"};
        for (String filename : filesToDelete) {
            try {
                Files.deleteIfExists(ROOT.resolve(filename));
            } catch (IOException ignored) {}
        }
    }

    private static void stopAll(List<Process> processList) {
        for (Process p : processList) {
            if (p != null && p.isAlive()) {
                p.destroy();
                try {
                    if (!p.waitFor(3, TimeUnit.SECONDS)) {
                        p.destroyForcibly();
                    }
                } catch (InterruptedException e) {
                    p.destroyForcibly();
                }
            }
        }
        processList.clear();
    }

    private static String env(String key, String defaultValue) {
        String val = System.getenv(key);
        return (val != null && !val.trim().isEmpty()) ? val.trim() : defaultValue;
    }

    private static void log(String message) {
        System.out.println("[" + java.time.LocalDateTime.now() + "] " + message);
    }

    private static boolean isCommandAvailable(String cmd) {
        try {
            Process p = new ProcessBuilder(cmd, "-v").start();
            return p.waitFor() == 0;
        } catch (Exception e) {
            return false;
        }
    }

    private static String getNpmCommand() {
        return OS.contains("win") ? "npm.cmd" : "npm";
    }

    private static String escapeJsString(String input) {
        if (input == null) return "";
        return input.replace("\\", "\\\\")
                    .replace("'", "\\'")
                    .replace("\"", "\\\"")
                    .replace("\n", "\\n")
                    .replace("\r", "\\r");
    }
}
